# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

display_url: https://the5thc.thrivex.xyz # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - label: Header
            name: header
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Background Image, name: backgroundImage, widget: image}
              - {label: Button Label, name: buttonLabel, widget: string}
              - {label: Video Embed Code, name: videoEmbedCode, widget: text}
          - label: Section 1
            name: section1
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Subtitle, name: subtitle, widget: string, required: false}
              - {label: Button Label, name: buttonLabel, widget: string, required: false}
              - {label: Button Link To, name: buttonLinkTo, widget: string, required: false}
          - label: Section 2
            name: section2
            widget: object
            required: false
            fields:
              - label: Featured Card
                name: featureCard
                widget: list
                fields:
                  - {label: Title, name: title, widget: string, required: false}
                  - {label: Image, name: image, widget: image, required: false}
                  - {label: Link To, name: linkTo, widget: string, required: false}
          - label: Section 3
            name: section3
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Subtitle, name: subtitle, widget: string, required: false}
              - {label: Background Image, name: backgroundImage, widget: image, required: false}
              - {label: Button Label, name: buttonLabel, widget: string, required: false}
              - {label: Button Link To, name: buttonLinkTo, widget: string, required: false}
          - label: Video Section
            name: section4
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Content, name: content, widget: markdown, required: false}
              - {label: Video Embed Code, name: videoEmbedCode, widget: text, required: false}
          - label: Featured Section
            name: section6
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - label: Logos
                name: logos
                widget: list
                fields:
                  - {label: Image, name: image, widget: image, required: false}
          - label: Contact Section
            name: section5
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Content, name: content, widget: markdown, required: false}
              - {label: Background Image, name: backgroundImage, widget: image, required: false}
              - {label: Button Label, name: buttonLabel, widget: string, required: false}
              - {label: Button Link To, name: buttonLinkTo, widget: string, required: false}


      - file: "content/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - label: Section 1
            name: section1
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Content, name: content, widget: markdown, required: false}
              - {label: Background Image, name: backgroundImage, widget: image, required: false}
              - {label: Quote Author, name: quoteAuthor, widget: string, required: false}
              - {label: Quote Author Title, name: quoteAuthorTitle, widget: string, required: false}
          - label: Section 2
            name: section2
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Image, name: image, widget: image, required: false}
          - label: Section 3
            name: section3
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Content, name: content, widget: markdown, required: false}
              - {label: Background Image, name: backgroundImage, widget: image, required: false}
              - {label: Button Label, name: buttonLabel, widget: string, required: false}
              - {label: Button Link To, name: buttonLinkTo, widget: string, required: false}

      - file: "content/pages/the-process.md"
        label: "The Process Page"
        name: "the-process-page"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Section
            name: section
            widget: list
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Content, name: content, widget: markdown, required: false}
              - {label: Button Label, name: buttonLabel, widget: string, required: false}
              - {label: Button LinkTo, name: buttonLinkTo, widget: string, required: false}
              - {label: Image, name: image, widget: image, required: false}

      - file: "content/pages/promotions.md"
        label: "Promotions Page"
        name: "promotions-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro Title, name: introTitle, widget: string}
          - {label: Intro Content, name: introContent, widget: text}

      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Intro Section
            name: introSection
            widget: object
            required: false
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Content, name: content, widget: markdown, required: false}
              - {label: Phone Label, name: phoneLabel, widget: string, required: false}
              - {label: Phone, name: phone, widget: string, required: false}
              - {label: Email Label, name: emailLabel, widget: string, required: false}
              - {label: Email, name: email, widget: string, required: false}
          - {label: Form Content, name: formContent, widget: string, required: false}
          - {label: Diamond Shapes (form option), name: diamondShapes, widget: string, required: false}

      - file: "content/pages/apply-now.md"
        label: "Apply Now Page"
        name: "apply-now-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Employment Options (form option), name: employmentOptions, widget: string, required: false}
          - {label: Monthly Income Options (form option), name: incomeOptions, widget: string, required: false}

  - name: promotions
    label: Promotion
    editor:
      preview: true
    folder: content/promotions
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ["Published", "Featured", "Draft"]
        default: 'Published'
      - {label: Date / Order, name: date, widget: date}
      - {label: Featured Image, name: featuredImage, widget: image, required: false}
      - {label: Content, name: body, widget: markdown}
      - {label: Content, name: body, widget: markdown}
      - label: 'Accordion Section'
        name: 'accordionSection'
        widget: 'object'
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - label: 'Accordion'
            name: 'accordion'
            widget: 'list'
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Content, name: content, widget: markdown, required: false}

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Twitter Site Account, name: twitterSiteAccount, widget: string, required: false}
              - {label: Twitter Creator Account, name: twitterCreatorAccount, widget: string, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}

      - file: "content/settings/social.yml"
        label: "Social Media Settings"
        name: "social-settings"
        fields:
          - {label: Instagram URL, name: instagram, widget: string, required: false}
          - {label: Facebook URL, name: facebook, widget: string, required: false}
